package com.cx.lost_found.dao;

import com.cx.lost_found.entity.FindDAO;

public interface FindDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    int insert(FindDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    int insertSelective(FindDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    FindDAO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(FindDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    int updateByPrimaryKeyWithBLOBs(FindDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    int updateByPrimaryKey(FindDAO record);
}