package com.cx.lost_found.dao;

import com.cx.lost_found.entity.LostDAO;

public interface LostDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lost
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lost
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int insert(LostDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lost
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int insertSelective(LostDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lost
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    LostDAO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lost
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(LostDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lost
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int updateByPrimaryKeyWithBLOBs(LostDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lost
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int updateByPrimaryKey(LostDAO record);
}