package com.cx.lost_found.dao;

import com.cx.lost_found.entity.MessageDAO;

public interface MessageDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    int insert(MessageDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    int insertSelective(MessageDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    MessageDAO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(MessageDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    int updateByPrimaryKeyWithBLOBs(MessageDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    int updateByPrimaryKey(MessageDAO record);
}