package com.cx.lost_found.dao;

import com.cx.lost_found.entity.MessageBoardDAO;

import java.util.List;

public interface MessageBoardDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageboard
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageboard
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    int insert(MessageBoardDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageboard
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    int insertSelective(MessageBoardDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageboard
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    MessageBoardDAO selectByPrimaryKey(Integer id);

    List<MessageBoardDAO> listMessages();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageboard
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    int updateByPrimaryKeySelective(MessageBoardDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageboard
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    int updateByPrimaryKey(MessageBoardDAO record);
}