package com.cx.lost_found.dao;

import com.cx.lost_found.entity.TypeDAO;

public interface TypeDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int insert(TypeDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int insertSelective(TypeDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    TypeDAO selectByPrimaryKey(Integer id);

    TypeDAO selectByType(String area);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TypeDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int updateByPrimaryKey(TypeDAO record);
}