package com.cx.lost_found.dao;

import com.cx.lost_found.entity.UserDAO;

public interface UserDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String telephone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int insert(UserDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int insertSelective(UserDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    UserDAO selectByPrimaryKey(String telephone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(UserDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    int updateByPrimaryKey(UserDAO record);
}