package com.cx.lost_found.dao;

import com.cx.lost_found.entity.UserDAO;

public interface UserDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri May 03 16:43:19 CST 2019
     */
    int deleteByPrimaryKey(String studentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri May 03 16:43:19 CST 2019
     */
    int insert(UserDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri May 03 16:43:19 CST 2019
     */
    int insertSelective(UserDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri May 03 16:43:19 CST 2019
     */
    UserDAO selectByPrimaryKey(String studentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri May 03 16:43:19 CST 2019
     */
    int updateByPrimaryKeySelective(UserDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri May 03 16:43:19 CST 2019
     */
    int updateByPrimaryKey(UserDAO record);
}