package com.cx.lost_found.entity;

public class AreaDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.areaname
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private String areaname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.id
     *
     * @return the value of area.id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.id
     *
     * @param id the value for area.id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.areaname
     *
     * @return the value of area.areaname
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.areaname
     *
     * @param areaname the value for area.areaname
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }
}