package com.cx.lost_found.entity;

import java.util.Date;

public class CommentDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.studentid
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    private String studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.msgid
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    private Integer msgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentTime
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    private Date commenttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.studentid
     *
     * @return the value of comment.studentid
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.studentid
     *
     * @param studentid the value for comment.studentid
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.msgid
     *
     * @return the value of comment.msgid
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    public Integer getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.msgid
     *
     * @param msgid the value for comment.msgid
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    public void setMsgid(Integer msgid) {
        this.msgid = msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment
     *
     * @return the value of comment.comment
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment
     *
     * @param comment the value for comment.comment
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentTime
     *
     * @return the value of comment.commentTime
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    public Date getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentTime
     *
     * @param commenttime the value for comment.commentTime
     *
     * @mbg.generated Fri May 03 21:26:06 GMT+08:00 2019
     */
    public void setCommenttime(Date commenttime) {
        this.commenttime = commenttime;
    }
}