package com.cx.lost_found.entity;

import java.util.Date;

public class FindDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.title
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.pictures
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private String pictures;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.status
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.time
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.area_id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.type_id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.user_telephone
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private String userTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.adminjudge
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private Integer adminjudge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.describe
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.id
     *
     * @return the value of find.id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.id
     *
     * @param id the value for find.id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.title
     *
     * @return the value of find.title
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.title
     *
     * @param title the value for find.title
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.pictures
     *
     * @return the value of find.pictures
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public String getPictures() {
        return pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.pictures
     *
     * @param pictures the value for find.pictures
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setPictures(String pictures) {
        this.pictures = pictures == null ? null : pictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.status
     *
     * @return the value of find.status
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.status
     *
     * @param status the value for find.status
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.time
     *
     * @return the value of find.time
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.time
     *
     * @param time the value for find.time
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.area_id
     *
     * @return the value of find.area_id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.area_id
     *
     * @param areaId the value for find.area_id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.type_id
     *
     * @return the value of find.type_id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.type_id
     *
     * @param typeId the value for find.type_id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.user_telephone
     *
     * @return the value of find.user_telephone
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public String getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.user_telephone
     *
     * @param userTelephone the value for find.user_telephone
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone == null ? null : userTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.adminjudge
     *
     * @return the value of find.adminjudge
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public Integer getAdminjudge() {
        return adminjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.adminjudge
     *
     * @param adminjudge the value for find.adminjudge
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setAdminjudge(Integer adminjudge) {
        this.adminjudge = adminjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.describe
     *
     * @return the value of find.describe
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.describe
     *
     * @param describe the value for find.describe
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }
}