package com.cx.lost_found.entity;

import java.util.Date;

public class FindDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.user_telephone
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private String userTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.title
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.uptime
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Date uptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.status
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.type_id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.area_id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.picture
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.findtime
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Date findtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.adminjudge
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Integer adminjudge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.description
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.id
     *
     * @return the value of find.id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.id
     *
     * @param id the value for find.id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.user_telephone
     *
     * @return the value of find.user_telephone
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public String getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.user_telephone
     *
     * @param userTelephone the value for find.user_telephone
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone == null ? null : userTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.title
     *
     * @return the value of find.title
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.title
     *
     * @param title the value for find.title
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.uptime
     *
     * @return the value of find.uptime
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.uptime
     *
     * @param uptime the value for find.uptime
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.status
     *
     * @return the value of find.status
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.status
     *
     * @param status the value for find.status
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.type_id
     *
     * @return the value of find.type_id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.type_id
     *
     * @param typeId the value for find.type_id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.area_id
     *
     * @return the value of find.area_id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.area_id
     *
     * @param areaId the value for find.area_id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.picture
     *
     * @return the value of find.picture
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.picture
     *
     * @param picture the value for find.picture
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.findtime
     *
     * @return the value of find.findtime
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Date getFindtime() {
        return findtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.findtime
     *
     * @param findtime the value for find.findtime
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setFindtime(Date findtime) {
        this.findtime = findtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.adminjudge
     *
     * @return the value of find.adminjudge
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Integer getAdminjudge() {
        return adminjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.adminjudge
     *
     * @param adminjudge the value for find.adminjudge
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setAdminjudge(Integer adminjudge) {
        this.adminjudge = adminjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.description
     *
     * @return the value of find.description
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.description
     *
     * @param description the value for find.description
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}