package com.cx.lost_found.entity;

import java.util.Date;

public class LostDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.title
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.pictures
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private String pictures;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.status
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.time
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.area_id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.type_id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.user_telephone
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private String userTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.adminjudge
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private Integer adminjudge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.describe
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.id
     *
     * @return the value of lost.id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.id
     *
     * @param id the value for lost.id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.title
     *
     * @return the value of lost.title
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.title
     *
     * @param title the value for lost.title
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.pictures
     *
     * @return the value of lost.pictures
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public String getPictures() {
        return pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.pictures
     *
     * @param pictures the value for lost.pictures
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setPictures(String pictures) {
        this.pictures = pictures == null ? null : pictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.status
     *
     * @return the value of lost.status
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.status
     *
     * @param status the value for lost.status
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.time
     *
     * @return the value of lost.time
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.time
     *
     * @param time the value for lost.time
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.area_id
     *
     * @return the value of lost.area_id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.area_id
     *
     * @param areaId the value for lost.area_id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.type_id
     *
     * @return the value of lost.type_id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.type_id
     *
     * @param typeId the value for lost.type_id
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.user_telephone
     *
     * @return the value of lost.user_telephone
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public String getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.user_telephone
     *
     * @param userTelephone the value for lost.user_telephone
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone == null ? null : userTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.adminjudge
     *
     * @return the value of lost.adminjudge
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public Integer getAdminjudge() {
        return adminjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.adminjudge
     *
     * @param adminjudge the value for lost.adminjudge
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setAdminjudge(Integer adminjudge) {
        this.adminjudge = adminjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.describe
     *
     * @return the value of lost.describe
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.describe
     *
     * @param describe the value for lost.describe
     *
     * @mbg.generated Wed May 01 18:07:20 GMT+08:00 2019
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }
}