package com.cx.lost_found.entity;

import java.util.Date;

public class LostDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.user_telephone
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private String userTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.title
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.uptime
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Date uptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.status
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.type_id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.area_id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.picture
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.losttime
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Date losttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.adminjudge
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private Integer adminjudge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost.description
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.id
     *
     * @return the value of lost.id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.id
     *
     * @param id the value for lost.id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.user_telephone
     *
     * @return the value of lost.user_telephone
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public String getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.user_telephone
     *
     * @param userTelephone the value for lost.user_telephone
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone == null ? null : userTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.title
     *
     * @return the value of lost.title
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.title
     *
     * @param title the value for lost.title
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.uptime
     *
     * @return the value of lost.uptime
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.uptime
     *
     * @param uptime the value for lost.uptime
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.status
     *
     * @return the value of lost.status
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.status
     *
     * @param status the value for lost.status
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.type_id
     *
     * @return the value of lost.type_id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.type_id
     *
     * @param typeId the value for lost.type_id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.area_id
     *
     * @return the value of lost.area_id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.area_id
     *
     * @param areaId the value for lost.area_id
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.picture
     *
     * @return the value of lost.picture
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.picture
     *
     * @param picture the value for lost.picture
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.losttime
     *
     * @return the value of lost.losttime
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Date getLosttime() {
        return losttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.losttime
     *
     * @param losttime the value for lost.losttime
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setLosttime(Date losttime) {
        this.losttime = losttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.adminjudge
     *
     * @return the value of lost.adminjudge
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public Integer getAdminjudge() {
        return adminjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.adminjudge
     *
     * @param adminjudge the value for lost.adminjudge
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setAdminjudge(Integer adminjudge) {
        this.adminjudge = adminjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost.description
     *
     * @return the value of lost.description
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost.description
     *
     * @param description the value for lost.description
     *
     * @mbg.generated Wed May 01 23:58:22 GMT+08:00 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}