package com.cx.lost_found.entity;

import java.util.Date;

public class MessageBoardDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messageboard.id
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messageboard.studentid
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    private String studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messageboard.uptime
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    private Date uptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messageboard.message
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messageboard.id
     *
     * @return the value of messageboard.id
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messageboard.id
     *
     * @param id the value for messageboard.id
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messageboard.studentid
     *
     * @return the value of messageboard.studentid
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messageboard.studentid
     *
     * @param studentid the value for messageboard.studentid
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messageboard.uptime
     *
     * @return the value of messageboard.uptime
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messageboard.uptime
     *
     * @param uptime the value for messageboard.uptime
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messageboard.message
     *
     * @return the value of messageboard.message
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messageboard.message
     *
     * @param message the value for messageboard.message
     *
     * @mbg.generated Mon May 06 14:48:36 CST 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}