package com.cx.lost_found.entity;

import java.util.Date;

public class MessageDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.user_telephone
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private String studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msgtype
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private Integer msgtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.title
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.uptime
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private Date uptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.status
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.type_id
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.area_id
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.picture
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.losttime
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private Date losttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.contact_name
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.contact_phone
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.adminjudge
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private Integer adminjudge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.description
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.user_telephone
     *
     * @return the value of message.user_telephone
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public String getStudentid() {
        return studentid;
    }

    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msgtype
     *
     * @return the value of message.msgtype
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public Integer getMsgtype() {
        return msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msgtype
     *
     * @param msgtype the value for message.msgtype
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setMsgtype(Integer msgtype) {
        this.msgtype = msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.title
     *
     * @return the value of message.title
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.title
     *
     * @param title the value for message.title
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.uptime
     *
     * @return the value of message.uptime
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.uptime
     *
     * @param uptime the value for message.uptime
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.status
     *
     * @return the value of message.status
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.status
     *
     * @param status the value for message.status
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.type_id
     *
     * @return the value of message.type_id
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.type_id
     *
     * @param typeId the value for message.type_id
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.area_id
     *
     * @return the value of message.area_id
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.area_id
     *
     * @param areaId the value for message.area_id
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.picture
     *
     * @return the value of message.picture
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.picture
     *
     * @param picture the value for message.picture
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.losttime
     *
     * @return the value of message.losttime
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public Date getLosttime() {
        return losttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.losttime
     *
     * @param losttime the value for message.losttime
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setLosttime(Date losttime) {
        this.losttime = losttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.contact_name
     *
     * @return the value of message.contact_name
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.contact_name
     *
     * @param contactName the value for message.contact_name
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.contact_phone
     *
     * @return the value of message.contact_phone
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.contact_phone
     *
     * @param contactPhone the value for message.contact_phone
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.adminjudge
     *
     * @return the value of message.adminjudge
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public Integer getAdminjudge() {
        return adminjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.adminjudge
     *
     * @param adminjudge the value for message.adminjudge
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setAdminjudge(Integer adminjudge) {
        this.adminjudge = adminjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.description
     *
     * @return the value of message.description
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.description
     *
     * @param description the value for message.description
     *
     * @mbg.generated Thu May 02 12:14:04 GMT+08:00 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}